### ISSUE TITLE
Patch up "unable to determine version" issue

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/ttrss-sandstorm#10]
I noticed the message at the bottom of preferences, and the hover message for it correlates with this very spammy message in the debug log:

![image](https://user-images.githubusercontent.com/4399499/88084428-0af3f500-cb4a-11ea-9699-007dc4d05891.png)

We should figure out how to suppress this.

**Comment by zenhack** [comment]
Looks like it's trying to use git to determine the version, so maybe if we include that in the app package.

Edit: nope, can confirm this happens even with git in the filesystem. Will have to investigate further.

**Comment by zenhack** [comment]
So I'm not actually sure what it *should* report there. per <https://tt-rss.org/#download>:

> Tiny Tiny RSS uses continuous development model based on git master branch which is considered stable. If possible, you should always be running latest master branch code.

Which is what I've been doing; this repo tracks ttrss upstream master. But that means there aren't any version numbers anymore, so I don't know what is expected to be displayed there.

~Perhaps noteworthy, the default theme doesn't include that text at all. So I wonder if this is upstream bitrot in the dark theme specifically?~ Edit: nvm, for some reason I remember this being the case but looking now it totally isn't; the default theme has this too.
