### ISSUE TITLE
Update daemon is not running

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/ttrss-sandstorm#11]
Upgraded my primary TTRSS grain to the experimental release, and this warning keeps popping up: "Update daemon is enabled in configuration, but daemon process is not running, which prevents all feeds from updating. Please start the daemon process or contact instance owner."

**Comment by ocdtrekkie** [comment]
Some stuff from the TTRSS System Log:
```


IP: 127.0.0.1 Request URI: /backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 | admin | 13:26
-- | -- | --
E_WARNING (2) | include/functions.php:1221 | file_get_contents(/var/lock/update_daemon.stamp): failed to open stream: No such file or directory IP: 127.0.0.1




E_WARNING (2) | include/functions.php:950 | DateTimeZone::__construct(): Unknown or bad timezone (America/Chicago)
-- | -- | --



E_USER_ERROR (256) | classes/db/mysqli.php:33 | Query SELECT DISTINCT 						date_entered, 						guid, 						ttrss_entries.id,ttrss_entries.title, 						updated, 						label_cache, 						tag_cache, 						always_display_enclosures, 						site_url, 						note, 						num_comments, 						comments, 						int_id, 						uuid, 						lang, 						hide_images, 						unread,feed_id,marked,published,link,last_read,orig_feed_id, 						last_marked, last_published, 						ttrss_feeds.title AS feed_title,favicon_avg_color, 						content,  						author,score 					FROM 						ttrss_entries,ttrss_user_entries 						LEFT JOIN ttrss_feeds ON (feed_id = ttrss_feeds.id) 					WHERE 					 					ttrss_user_entries.ref_id = ttrss_entries.id AND 					ttrss_user_entries.owner_uid = '1' AND 					 					 					 					 					 					true ORDER BY score DESC, date_entered DESC, updated DESC 					LIMIT 200 OFFSET 0 failed: Incorrect key file for table '/tmp/#sql_2a_0.MYI'; try to repair it | admin | Jul 25, 23:22
-- | -- | -- | -- | --

```

**Comment by zenhack** [comment]
Found this when investigating the last message:

https://stackoverflow.com/questions/2011050/mysql-126-incorrect-key-file-for-table

So maybe you're running out of space in `/tmp`? Will need to think about what to do about that it.

Second error is because apparently /usr/share/zoneinfo/America/Chicago didn't get picked up by spk dev; I just pushed a commit that fixes that.

**Comment by ocdtrekkie** [comment]
Update daemon one seems to be what is breaking my grain though.

Seems weird my tmp would overfill that fast.

**Comment by ocdtrekkie** [comment]
Okay, just tried opening the thing again and all the Powerbox entries came flowing through. So my grain isn't completely broken, it just didn't behave when I expected it to.

**Comment by zenhack** [comment]
My hunch was that the daemon had died *because* it was out of space. Are you still getting error messages about the daemon?

**Comment by ocdtrekkie** [comment]
Yep. Presumably since tmp is ethereal, it works from time to time but also fills up and dies?

**Comment by zenhack** [comment]
Just saw this error message on one of my own grains, but it subsequently (without me restarting or doing anything) did a feed update, so I thin there's a mis-diagnosis happening here; the daemon does appear to be running, but for some reason ttrss thinks it isn't and is reporting suprrious errors?

**Comment by ocdtrekkie** [comment]
It's looking for /var/lock/update_daemon.stamp ...I wonder if that file exists in the grain or not.

**Comment by zenhack** [comment]
It does on mine. I wonder if we're hitting a race condition where it's
just doing the check before the daemon is ready. Maybe I'll futz with
the order things are started in launcher.sh

Quoting Jacob Weisz (2020-07-29 09:37:48)

**Comment by zenhack** [comment]
I think I've solved the problem; pushed a new spk to the market, please test. (Please still do not actually publish it)

**Comment by ocdtrekkie** [comment]
I don't think I'm seeing this anymore at all.
