### ISSUE TITLE
My favicons didn't translate over

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/ttrss-sandstorm#12]
Not a big deal at all, but I would note that all of my favicons are broken images since the update. You can upload them yourself in "Edit feed", so I am going to grab them from my grain backup and manually put them in.

**Comment by zenhack** [comment]
Problem wasn't that they weren't being fetched, but that nginx wasn't configured to serve the directory they were stored in. Just pushed a commit that fixes this.

**Comment by ocdtrekkie** [comment]
Ah, glad I reported this then... I suspect uploading my own wouldn't have worked either then.
