### ISSUE TITLE
tt-rss never loads after last upgrade

### ISSUE THREAD

**Issue by voidplayer** [zenhack/ttrss-sandstorm#13]
You can see the loading icon of the grain but it nevers gets to load

Logs are filled with this message several times per second
```waiting for update-daemon to be available at /var/lock/update_daemon.stamp.```

After a while i get this message
```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server
```

Other grains work fine

**Comment by voidplayer** [comment]
I can read this on the log tt-rss log right before ```wating...```

```Schema version is wrong, please upgrade the database (--update-schema)```

**Comment by ocdtrekkie** [comment]
It should've asked you to upgrade the first time you opened it after updating? Do you recall that, and did anything odd happen then?

**Comment by ocdtrekkie** [comment]
@zenhack I didn't test what would happen going from the super old version to when you fixed my update-daemon issue.

Is it possible that pre-schema upgrade, waiting for that daemon is a problem?

**Comment by voidplayer** [comment]
Interface asked me if i wanted to update tt-rss. I clicked it and next thing it doesnt load. Nothing else happened

**Comment by voidplayer** [comment]
I tried refreshing the grain. Opening and closing it and restarting the server, but its the same

**Comment by voidplayer** [comment]
I can try to upgrade the schema manually to see if thats the problem, but i would need directions, because i dont know how to do that :)

**Comment by ocdtrekkie** [comment]
I suspect I know where the issue lies, and if so, Ian should be able to fix it.

**Comment by zenhack** [comment]
I suspect @ocdtrekkie's hypothesis is correct; probably the update daemon is failing to start because of the need to migrate, and then we're blocking waiting on the update daemon to start... so it just hangs.

Unfortunately I don't think I have the old spk hanging around anywhere to create a grain and test with, but I built an updated spk here:

https://thelibrary.sandcats.io/shared/3jF9SEBTxVbs9ZQ2hNpCso4RYe1O1GbWyXQAssDSIyI

Which I *think* should solve the problem, if you want to test it (the patch has been pushed to the `fix-13` branch in this repo).

Sorry about this!

**Comment by ocdtrekkie** [comment]
I can get you an old SPK for testing purposes if you need it. (The app market will still even serve it if I look up the packageId, I believe.)

**Comment by zenhack** [comment]
That would be useful, please do.

**Comment by ocdtrekkie** [comment]
https://app-index.sandstorm.io/packages/f83ab3b543c81303227fb0d793bf8daa should be TTRSS appVersion 10.

**Comment by zenhack** [comment]
Tested, it successfully updates and boots from both older versions. @ocdtrekkie, just pushed it to the market, review and approve when you can.

**Comment by ocdtrekkie** [comment]
Approved to the live market.

**Comment by zenhack** [comment]
Great. @voidplayer, you should get another ttrss update soon which should fix the problem.

**Comment by ocdtrekkie** [comment]
If you don't want to wait a day for the notification, you can also go and "Install" TTRSS again from the App Market, but in that case you would both need to "Upgrade app" and then, from the app page "Upgrade grains". Waiting for the notification is a tiny bit more straightforward. ;)

**Comment by voidplayer** [comment]
I reinstalled ttrss from the app market but i couldnt find the "upgrade grains". I searched every menu...

Ill just wait for the notification :)

A new created ttrss grain seemed to work tho :+1:

**Comment by ocdtrekkie** [comment]
@voidplayer "Upgrade grains" is available on the app page. Go to the Apps tab on Sandstorm, and click The TTRSS icon. It will have a dialog saying not all of your TTRSS grains are using the latest version and have the button to upgrade them.

(You won't get a tray notification if you already installed the latest version.)

**Comment by voidplayer** [comment]
Okay, i clicked again in the market and then install again (a second time) and then it took me to the ttrss instances and THEN i got an upgrade notification

Then i had to restart the grain and then it finally prompted me to upgrade the database

It seems to be working now. Thanks guys!!

**Comment by zenhack** [comment]
No problem! Sorry again for the mishap.

Quoting voidplayer (2020-08-10 19:03:26)
