### ISSUE TITLE
Warnings/issues in experimental version

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/ttrss-sandstorm#20]
First of all... As the case is, I ended up testing this by upgrading a grain that was "OG" from the original package. Which is nice anyways to make sure we haven't lost where we should be. If I use the "debug grain" method, I can force some Powerboxes, but I got no "stream of Powerboxes" like I recall when it tried doing a feed update. ...I'm not really seeing a feed update happen, I think? Powerboxes work when I use debug to force them, so it's an issue on the TTRSS side. I found these interesting warnings:

```
[21-Sep-2020 18:00:32] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_intl.dll' - /usr/lib/php/20151012/php_intl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[21-Sep-2020 18:00:32] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_mbstring.dll' - /usr/lib/php/20151012/php_mbstring.dll: cannot open shared object file: No such file or directory in Unknown on line 0
```

This is of course, kinda weird, because intl.so and mbstring.so exist... and DLLs are Windows files.

**Comment by zenhack** [comment]
Those warnings were there before, I've been meaning to investigate, but I doubt that's responsible for the issues you're seeing.

**Comment by zenhack** [comment]
Fixed the mbstring warnings.

Can you confirm that you still get those pb requests when upgrading from an old grain to current stable? I have a hunch we may have actually broken this before now, when fiddling with other issues.

**Comment by ocdtrekkie** [comment]
Not easily, it was happenstance that I had an old version of my grain on Alpha that I tested against. But the thing I definitely found interesting is that if I forced a feed to update with "debug feed", it definitely gave me my Powerbox and updated the feed with the latest articles. It just doesn't seem to be refreshing feeds outside of that.

**Comment by zenhack** [comment]
Wait, is it not refreshing the feeds *at all* or just on startup?

**Comment by ocdtrekkie** [comment]
At all, as far as I can tell.

I just took a copy of my grain running your current stable, restored it to Alpha where I am testing... and it appears to be staying out of date. My original grain on my personal server already has newer articles on the same feeds, but the grain running on Alpha with the experimental release does not.

**Comment by ocdtrekkie** [comment]
Actually, another fun derailment:

The grain I had upgraded from the original packaging: It wasn't attempting to refresh all feeds, but would issue individual Powerbox requests when I "debug feed" them.

The grain I just restored from my copy of the current stable package of yours looks like it did just try to refresh all feeds, 500 error'd out of all of them, and doesn't work when I "debug feed" them. They should presumably be asking for the Powerbox again since I restored this grain from another server... but when I debug they 500 immediately.

**Comment by zenhack** [comment]
Ah I bet I know what's happening -- probably we need to add some fall back logic such that if restoring a capability fails, we junk the capability and try to get new one. Presumably it's trying to use the token it has saved in the database, but that token isn't valid for the new grain so it's failing.

Can you reproduce any of this without restoring a backup of a grain that had already been given capabilities? If not, I don't think this has to block release, as it isn't actually a regression.

**Comment by ocdtrekkie** [comment]
I'll probably need to do a bit of completely green-field testing... I really don't wanna break my one TTRSS grain I use by testing with it. :P

**Comment by ocdtrekkie** [comment]
So, TTRSS package 18 does not appear to work at all on testing.

I created fresh grains on Alpha of Jason's TTRSS 10 (and then upgraded it to 17) and TTRSS 17, and added an RSS feed to both. While they didn't fetch immediately, they did fetch on the next grain load, and as I use 17 regularly, I'm reasonably confident this version works well enough.

A fresh TTRSS 18 grain does not fetch the feeds at all. Furthermore, the Mobile App tab just shows `{"error":{"code":6,"message":null}}` instead of the usual information for connecting apps there.

**Comment by ocdtrekkie** [comment]
As I noted previously, while the experimental package does not appear to successfully fetch on it's own, if I right-click a feed, Debug Feed, and Continue on that, it will pull the feed.

**Comment by ocdtrekkie** [comment]
All my test grains are upgraded to that package, and I'm now going to let them sit and see if they auto-update or anything. The test feeds I use are on my working grain too, so I can compare against it tomorrow.

**Comment by zenhack** [comment]
Ok, I'll stare at this some tomorrow. Let me know whether stuff auto updates after a while.

**Comment by ocdtrekkie** [comment]
So, my test grains did update after a while, but I think partially because I did the "Debug grain" thing. When I made another fresh grain on the latest version, added the feed URL (and granted the Powerbox request), and then left it for a few hours, it did nothing.

**Comment by ocdtrekkie** [comment]
You can see here that it accessed the feed to get the feed name, after the Powerbox request was made, but that the feeds were never updated:
![image](https://user-images.githubusercontent.com/4399499/103837810-1b911c80-5051-11eb-955b-bc71b1cbd0ba.png)

**Comment by zenhack** [comment]
As discussed on IRC, the feed update issues went away after I pulled in the latest ttrss changes, so maybe this was a regression upstream that has since been fixed.

I just fixed the mobile page issue and pushed a fix to the app market. Please review when you get a chance.

**Comment by ocdtrekkie** [comment]
I am going to close the issue, I think the feed behavior seems to be a fair bit healthier, yes. I will play with my test grains a bit more, upgrade my main TTRSS and verify nothing new exploded, and then approve, hopefully tomorrow.
