### ISSUE TITLE
powerbox request fails with error 500

### ISSUE THREAD

**Issue by voidplayer** [zenhack/ttrss-sandstorm#28]
![image](https://user-images.githubusercontent.com/4019910/129798180-6dc66843-9ed5-405d-a113-847ae38974d3.png)

At first i thought it wasnt responsive because after you click on the ```use...``` , it does nothing for very long time. But while debugging this, i got the 500 to show up

And this shows in the log

```
Exception while invoking method 'newFrontendRef' Error: getaddrinfo EAI_AGAIN pump2rss.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:74:26)

```

Basically, dns doesnt respond and powerbox keeps asking everytime for it because you have to close the request without accepting it (and you have no idea why is failing anyway)

Im not sure what i want to happen here, but something that allows me to debug it without having to look at the logs. Or maybe just allow powerbox dialog to accept even if the dns doesnt exist

Thanks for keeping this alive!

**Comment by zenhack** [comment]
Thanks for the report. Yeah, this is a sandstorm bug:

https://github.com/sandstorm-io/sandstorm/issues/3388

I'm going to close this since this isn't a ttrss issue, and we've already got a ticket for it.

> Thanks for keeping this alive!

You're welcome!
