### ISSUE TITLE
Clean up Mobile App page

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/ttrss-sandstorm#9]
This page added in Jason's port needs some cleanup:

- [x] I have no idea why the "Mobile App" tab has all that space
- [x] Offer template styling needs to be updated to be readable on the dark style here
- [x] The Windows TTRSS client that I added here is sadly no longer available from the Microsoft Store, it still works fantastically (I use it daily), but unless you have the appx file, you're out of luck, so we should probably remove that section
- [ ] It would be good to maybe validate a couple other apps for various platforms that can handle HTTP Basic Auth TTRSS and work with the Sandstorm package

![image](https://user-images.githubusercontent.com/4399499/88084057-6d98c100-cb49-11ea-8d72-baad176012a3.png)

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2020-07-21 13:01:14)

>      * I have no idea why the "Mobile App" tab has all that space

This appears to be unique to my version; the version currently in the
app market does the right thing here, so probably something changed that
it's interacting badly with.

>      * Offer template styling needs to be updated to be readable on the
>        dark style here
>      * The Windows TTRSS client that I added here is sadly no longer
>        available from the Microsoft Store, it still works fantastically (I
>        use it daily), but unless you have the appx file, you're out of
>        luck, so we should probably remove that section
>      * It would be good to maybe validate a couple other apps for various
>        platforms that can handle HTTP Basic Auth TTRSS and work with the
>        Sandstorm package

+1

**Comment by zenhack** [comment]
whitespace issue turned out to be due to a missing icon; fixed.

**Comment by zenhack** [comment]
Looks like the only reason the styling wasn't a problem for jason's package is because the ttrss theme wasn't being applied to the preferences as a whole. The fix is to somehow get the user's theme css to apply to the contents of the offer iframes.

**Comment by zenhack** [comment]
I tested this with two different android clients from F-droid. More reports welcome, but I'm pretty sure it's working.

**Comment by ocdtrekkie** [comment]
I think we should move the offer templates to the top of the page and have app-independent instructions there. And below link apps tested to work for various platforms.

Back years ago I had a hard time finding TTRSS clients that supported HTTP Basic Auth.

Note: I use an app called Fiery Feeds on iOS which works well with the Sandstorm version but nags paying for premium often.

**Comment by zenhack** [comment]
Do we need to do anything else before closing this? As I said I'm pretty comfy with the http auth testing.

**Comment by ocdtrekkie** [comment]
I'd like to make the instructions not Android specific and be clear these are the credentials and then offer more choices for what apps. But I don't see that as a blocker for release.

**Comment by zenhack** [comment]
Alright, I'm going to remove the milestone then but I'll leave it open.
